---
language: python
python: "2.7"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-apt python-pycurl
install:
  # Install Ansible.
  - pip install ansible

  # Add ansible.cfg to pick up roles path.
  - "printf '[defaults]\nroles_path = ../' > ansible.cfg"

  # Install dependencies.
  - ansible-galaxy install geerlingguy.mysql
  - ansible-galaxy install geerlingguy.apache
  - ansible-galaxy install geerlingguy.php
  - ansible-galaxy install geerlingguy.php-mysql       
  - ansible-galaxy install geerlingguy.phpmyadmin   

script:
  - ansible --version
#  - export ANSIBLE_ROLES_PATH="../"
#  - echo localhost > inventory
  - ansible-playbook -i hosts --syntax-check web.yml
  - ansible-playbook -i hosts --connection=local --sudo -vvvv web.yml
