---
# These tasks are responsible for copying the latest dev/production code from
# the version control system.

- name: Web | Copy the code from repository
  git: repo={{ repository }} version={{ repository_version }} dest={{ web_base_dir }}/

- name: Web | Creates the index.php file
  template: src=index.php.j2 dest={{ web_base_dir }}/index.php
  when: php_enable

#See result at http://localhost:{{apache_listen_port}}/
