---
# These tasks are responsible for copying the latest dev/production code from
# the version control system.

- name: Web | Copy the code from repository
  git: repo={{ repository }} version={{ repository_version }} dest={{ web_base_dir }}/
  ignore_errors: yes  
  become: yes

- name: Web | Creates the index.php file
  template: src=index.php.j2 dest={{ web_base_dir }}/index.php
  when: php_enable
  become: yes

- name: Web | Change destination directory ownership
  file:
    dest="{{ web_base_dir }}/"
    state=directory
    owner="{{ apache_owner }}"
    group="{{ apache_group }}"
  ignore_errors: true
  become: yes
  
#See result at http://localhost:{{apache_listen_port}}/
