---
# These tasks install http and the php modules.

#- name: Web | insert iptables rule for httpd
#  lineinfile: dest=/etc/sysconfig/iptables state=present regexp="{{ httpd_port }}" insertafter="^:OUTPUT "
#              line="-A INPUT -p tcp  --dport {{ httpd_port }} -j  ACCEPT"
#  notify: restart iptables

- name: Web | Enable some required modules rewrite vhost_alias expires (cache) headers deflate (compress)
  action: command a2enmod rewrite vhost_alias expires headers mime autoindex deflate ssl
  
- name: Web | Enable some required advanced modules proxy
  action: command a2enmod proxy proxy_ajp proxy_http  proxy_balancer proxy_connect proxy_html

- name: Web | Install php for apache
  action: "{{ ansible_pkg_mgr }} name={{ item }} state={{ util_pkg_state|default('present') }} update_cache=yes"
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  with_items:
   #- php5
   #- libapache2-mod-php5 
   - php7.0-dev 
   - php7.0-cli  
   - libapache2-mod-fastcgi
   - libapache2-mod-php7.0

- name: Web | Install perl for apache
  action: "{{ ansible_pkg_mgr }} name={{ item }} state={{ util_pkg_state|default('present') }} update_cache=yes"
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  with_items:
   - libapache2-mod-perl2

- name: Web | http (apache) service state
  service: name=httpd state=started enabled=yes
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Web | http (apache) service state
  service: name=apache2 state=started enabled=yes
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Web | Disable the awx site
  action: command a2dissite awx-httpd-7077
#  ignore_errors: yes
  tags: apache

- name: Web | Disable the jenkins site
  action: command a2dissite jenkins
#  ignore_errors: yes
  tags: apache

- name: Web | Enable the default site
  action: command a2ensite 000-default
#  ignore_errors: yes
  tags: apache

#- name: Web | Configure SELinux to allow httpd to connect to remote database
#  seboolean: name=httpd_can_network_connect_db state=true persistent=yes

- name: Web | Add apache letsencrypt configuration.
  template:
    src: "le.conf.j2"
    dest: "{{ apache_conf_path }}/sites-available/e.conf"
    owner: root
    group: root
    mode: 0644
  become: yes
#  notify: restart apache
  when: (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu') and apache_create_vhosts

- name: Web | Enable the letsencrypt site
  action: command a2enconf le
  tags: apache

#look result at : https://localhost/html/
