---
# These tasks install http and the php modules.

- name: Web | Install http (apache) and php etc)
  yum: name={{ item }} state=present
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'    
  with_items:
   - httpd
   - php
   - php-mysql
   - git
   - libsemanage-python
   - libselinux-python

- name: Web | Install http (apache) and php etc)
  apt: pkg={{ item }} state=present
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'  
  with_items:
   - apache2
   - php5
   - libapache2-mod-php5
   - git
#   - libsemanage-python
#   - libselinux-python

#- name: Web | insert iptables rule for httpd
#  lineinfile: dest=/etc/sysconfig/iptables state=present regexp="{{ httpd_port }}" insertafter="^:OUTPUT "
#              line="-A INPUT -p tcp  --dport {{ httpd_port }} -j  ACCEPT"
#  notify: restart iptables

- name: Web | http (apache) service state
  service: name=httpd state=started enabled=yes
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'    

- name: Web | http (apache) service state
  service: name=apache2 state=started enabled=yes
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'  

- name: Web | Enable the default site
  action: command a2ensite 000-default
#  ignore_errors: yes
  tags: apache

#- name: Web | Configure SELinux to allow httpd to connect to remote database
#  seboolean: name=httpd_can_network_connect_db state=true persistent=yes 

#look result at : https://localhost/html/
