---

- include: user.yml

#below apache installation has been moved to apache role
#- include: install_httpd.yml

- include: copy_code.yml

- include: share.yml

- name: Copy Dockerfile
  template: src=Dockerfile.j2 dest={{ docker_files_generated_directory }}/Dockerfile mode=0777
  when: docker_files_enable

- name: Copy build.sh
  template: src=build.sh.j2 dest={{ docker_files_generated_directory }}/build.sh mode=0777
  when: docker_files_enable
