
##
 # Jenkins user
 #

#- name: Kill connection used by user jenkins
#  action: shell killall -u {{ jenkins_user }} || true
#  changed_when: false
#  become: yes
#  ignore_errors: true

#TODO https://stackoverflow.com/questions/26677064/create-and-use-group-without-restart

- name: jenkins-slave | Create a jenkins group
  group:
      name={{ jenkins_group }}
      state=present
      gid={{ jenkins_gid }}
  become: yes

- name: jenkins-slave | Create a www-data group
  group:
      name={{ data_group }}
      state=present
      gid={{ data_gid }}
  become: yes
  ignore_errors: true

- name: jenkins-slave | Create jenkins user
  user: name={{ jenkins_user }} 
        password={{ jenkins_password }} 
        update_password=always 
        comment="Jenkins user" 
        home={{ jenkins_home }} 
        shell={{ jenkins_shell }} 
        uid=2000
        groups={{ jenkins_groups }}
#  become: yes
  ignore_errors: true
